type: Heimdall.fe.BinningFe

args:
  embedding_cls: torch.nn.Linear # TODO: replace this with the actual scGPT ValueEncoder: https://github.com/bowang-lab/scGPT/blob/7301b51a72f5db321fccebb51bc4dd1380d99023/scgpt/model/model.py#L765
  num_embeddings: 10 # Number of bins
  d_embedding: 128 #
