type: Heimdall.fc.AdmixtureFc

args:
  max_input_length: 2048
  species: ${dataset.preprocess_args.species}
  ensembl_dir: ${data_path}
  gene_metadata_filepath: ${data_path}/gene_metadata/species_chrom.csv
  embedding_parameters:
    type: Heimdall.embedding.GaussianInitEmbedding
    args:
      num_embeddings: 100
      embedding_dim: ${fg.args.d_embedding}
  tailor_config:
    # type: Heimdall.tailor.ReorderTailor
    type: Heimdall.tailor.AdmixtureTailor
  order_config:
    type: Heimdall.order.ExpressionOrder
  reduce_config:
    type: Heimdall.reduce.AdmixtureSumReduce
