args:
  task_type: multiclass
  label_col_name: task_celltype
  metrics:
    - Accuracy
    - MatthewsCorrCoef
  shuffle: true
  batchsize: 32
  epochs: 20
  # TODO: prepare predefined splits (https://github.com/gkrieg/Heimdall/issues/51)
  # splits:
  #   type: predefined
  #   keys_:
  #     train: train
  #     val: val
  #     test: test
  dataset_config:
    type: Heimdall.datasets.SingleInstanceDataset
