args:
  task_type: classification
<<<<<<< HEAD
  task_structure: single
  label_col_name: task_celltype
=======
  label_col_name: class
>>>>>>> origin/main
  metrics:
    - Accuracy
    - MatthewsCorrCoef
  train_split: 0.8
  shuffle: true
  batchsize: 32
  epochs: 10
<<<<<<< HEAD
  prediction_dim: 14
=======
  prediction_dim: 20
  dataset_config:
    type: Heimdall.datasets.SingleInstanceDataset
>>>>>>> origin/main
