args:
  task_type: multiclass
  task_structure: paired
  interaction_type: task_ko
  splits: predefined # will automatically search for the train/val/test masks, otherwise will use "random"
  metrics:
    - Accuracy
  train_split: 0.8
  shuffle: true
  batchsize: 32
  epochs: 10
