dataset_name: "find_out_perturbation"

preprocess_args:
  data_path: "/work/magroup/scllm/datasets/perturb_seq_norman.h5ad"
  top_n_genes: 1000
  normalize: true
  log_1p: true
  scale_data: true
  species: 'human'